// Code generated by goctl. DO NOT EDIT.
// Source: serve.proto

package server

import (
	"context"

	"serve/internal/logic"
	"serve/internal/svc"
	"serve/serve"
)

type ServeServer struct {
	svcCtx *svc.ServiceContext
	serve.UnimplementedServeServer
}

func NewServeServer(svcCtx *svc.ServiceContext) *ServeServer {
	return &ServeServer{
		svcCtx: svcCtx,
	}
}

func (s *ServeServer) PostGameInformation(ctx context.Context, in *serve.GameInformationRequest) (*serve.GameInformationRequestResponse, error) {
	l := logic.NewPostGameInformationLogic(ctx, s.svcCtx)
	return l.PostGameInformation(in)
}

func (s *ServeServer) InquireBestEdge(ctx context.Context, in *serve.InquireBestEdgeRequest) (*serve.InquireBestEdgeResponse, error) {
	l := logic.NewInquireBestEdgeLogic(ctx, s.svcCtx)
	return l.InquireBestEdge(in)
}
